### ISSUE TITLE
python was not found in the pkg-config search path

### ISSUE THREAD

**Issue by blegat** [rdeits/LCMCore.jl#7]
The build fails on ArchLinux :(
I get
```
Package python was not found in the pkg-config search path.
Perhaps you should add the directory containing `python.pc'
to the PKG_CONFIG_PATH environment variable
No package 'python' found
```
It seems that `pkg-config` does not work for `python` but works for `python3` and `python2`.
```
$ pkg-config --cflags python 
Package python was not found in the pkg-config search path.
Perhaps you should add the directory containing `python.pc'
to the PKG_CONFIG_PATH environment variable
No package 'python' found
$ pkg-config --cflags python3
-I/usr/include/python3.6m
$ pkg-config --cflags python2
-I/usr/include/python2.7
```
If I remove the validator for `python` then the build completes successfully.
Would it be appropriate to check for `python`, `python2` and `python3` in the validator and return `true` if at least one works ?

**Comment by rdeits** [comment]
Sure, that seems totally reasonable. The reason this validator exists is to ensure that you have `python-dev` installed, rather than just `python`. I couldn't think of a cleaner way to do that within BinDeps.
