### ISSUE TITLE
BinDeps.jl finding system Python

### ISSUE THREAD

**Issue by dehann** [rdeits/LCMCore.jl#9]
Hi Robin,

We are fussing with [build.jl](https://github.com/rdeits/LCMCore.jl/blob/bf6d67c/deps/build.jl#L21), because we don't want to use system Python when installing ```lcm```.

We came onto this because we would like to use python provided by ```.julia/v0.5/Conda```. I think this is not happening. The possibly offending line above is grabbing system python via ```BinDeps.library_dependency```.

please see output from @pvazteixeira below...

**Comment by pvazteixeira** [comment]
Notice that LCMCore is building against
```julia
INFO: Building LCMCore
-I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 
-I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 
-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include 
-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include 
```
while Julia is using the Conda.jl-provided python.

```julia
julia> Pkg.add("PyLCM")
INFO: Cloning cache of CMakeWrapper from https://github.com/rdeits/CMakeWrapper.jl.git
INFO: Cloning cache of DataStructures from https://github.com/JuliaCollections/DataStructures.jl.git
INFO: Cloning cache of LCMCore from https://github.com/rdeits/LCMCore.jl.git
INFO: Cloning cache of Parameters from https://github.com/mauro3/Parameters.jl.git
INFO: Cloning cache of PyLCM from https://github.com/rdeits/PyLCM.jl.git
INFO: Installing CMakeWrapper v0.0.2
INFO: Installing DataStructures v0.5.3
INFO: Installing LCMCore v0.0.3
INFO: Installing Parameters v0.7.2
INFO: Installing PyLCM v0.1.0
INFO: Building CMakeWrapper
INFO: Attempting to Create directory /home/pvt/.julia/v0.5/CMakeWrapper/deps/downloads
INFO: Downloading file https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 29.2M  100 29.2M    0     0  8197k      0  0:00:03  0:00:03 --:--:-- 8195k
INFO: Done downloading file https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz
INFO: Attempting to Create directory /home/pvt/.julia/v0.5/CMakeWrapper/deps
INFO: Directory /home/pvt/.julia/v0.5/CMakeWrapper/deps already created
INFO: Attempting to Create directory /home/pvt/.julia/v0.5/CMakeWrapper/deps/usr/bin
cmake version 3.7.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
INFO: Building LCMCore
-I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 
-I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 
-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include 
-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include 
INFO: Building Conda
INFO: Building PyCall
INFO: Using the Python distribution in the Conda package by default.
To use a different Python version, set ENV["PYTHON"]="pythoncommand" and re-run Pkg.build("PyCall").
Fetching package metadata .............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/pvt/.julia/v0.5/Conda/deps/usr:
#
numpy                     1.12.1                   py27_0  
INFO: PyCall is using /home/pvt/.julia/v0.5/Conda/deps/usr/bin/python (Python 2.7.13) at /home/pvt/.julia/v0.5/Conda/deps/usr/bin/python, libpython = /home/pvt/.julia/v0.5/Conda/deps/usr/lib/libpython2.7
INFO: /home/pvt/.julia/v0.5/PyCall/deps/deps.jl has not changed
INFO: /home/pvt/.julia/v0.5/PyCall/deps/PYTHON has not changed
INFO: Package database updated
```

**Comment by dehann** [comment]
Looks like whats happening is when we install ```PyLCM```, ```BinDeps.library_dependency``` is going through system python. However, when running ```PyLCM``` or ```PyCall```, it uses the python provided Conda.jl, and ```lcm``` is not in the ```.julia/v0.5/Conda/deps/usr/pkgs``` folder.

**Comment by dehann** [comment]
Maybe you can try this by you, I get:
```julia
using PyCall
@pyimport sys
sys.executable
```
to which I get:
```
"/usr/bin/python"
```
However Pedro is trying to set in Julia ```ENV["PYTHON"]=""``` which is where the fun starts.

**Comment by rdeits** [comment]
Thanks for reporting this. I'm not yet sure what the right fix is, but I'm sure we can figure something out.

If PyLCM were responsible for building LCM itself, then this would be easier to fix. We could just check `sys.executable` and then tell LCM to build with that particular version of python. Unfortunately, I've structured PyLCM to rely on LCMCore for its build. But LCMCore might be built before PyCall is even installed, so it has no access to the python that PyCall will use.

I think that the only way to resolve this is to have PyLCM be responsible for building the LCM Python bindings. That's probably the right thing to do anyway. I'll look into it.

**Comment by dehann** [comment]
Personally I think we should start thinking about LCM2.0 where you have a few ENUM bytes at the beginning of the payload to identify which serialization technique is being used. There is plenty support for encoding and decoding functions out there in the wild, and would reduce the cost of trying to keep PyLCM around.

@pvazteixeira and I started playing around with [this example file](https://github.com/dehann/LCMCore.jl/blob/master/examples/LCMproto.jl) using ```ProtoBuf.jl``` and ```JSON.jl```. ```ProtoBufs``` have nice size and forward-backward compatibility features.
```
ProtoBuf
MsgPack
JSON
BSON # also uses enum for packed types btw
LCM
Cap`n Proto
etc...
```

As an interim solution, we should maybe think about Julia as an option to lcm-gen. But ultimately, using standard serialization techniques we can all get access to much broader language support, beyond ```lcm-gen```. My 2 cents.

**Comment by rdeits** [comment]
Love it :smile: 

I'm using something a bit like that over at DrakeVisualizer.jl: I'm still sending LCM messages, but the only LCM type I use is just a struct containing a format identifier and a blob of bytes. Having that idea built into the protocol would be even better. I wonder if the [ZCM](https://github.com/ZeroCM/zcm) people would be interested as well.

**Comment by rdeits** [comment]
I have a potential solution here: #17

**Comment by rdeits** [comment]
Is this still relevant? Did the fix in PyLCM resolve the issue for you?

**Comment by dehann** [comment]
I think so, thanks.
